### ISSUE TITLE
communication_constraints_violation

### ISSUE THREAD

**Issue by byeongkyu** [frankaemika/franka_ros2#108]
```
...

[ros2_control_node-6] [ERROR] [1739844272.283399633] [franka.franka_robot_state_broadcaster]: Failed to lock the realtime publisher after 10 attempts                                                                                                     
[ros2_control_node-6] [ERROR] [1739844272.283458191] [franka.controller_manager]: The update call of the following controller returned an error: 'franka_robot_state_broadcaster'                                                                         
[ros2_control_node-6] terminate called after throwing an instance of 'franka::ControlException'                                                                                                                                                           
[ros2_control_node-6]   what():  libfranka: Move command aborted: motion aborted by reflex! ["communication_constraints_violation"]                                                                                                                       
[ros2_control_node-6] Stack trace (most recent call last) in thread 1767:                                                                                                                                                                                 
[ros2_control_node-6] #18   Object "", at 0xffffffffffffffff, in              

...
```

Kernel: 6.8.2-rt11 #1 SMP PREEMPT_RT
FCI: 5.7.2
libfranka: 0.15.0
ROS2: humble

Self ping test: 
```
10000 packets transmitted, 10000 received, 0% packet loss, time 10089ms
rtt min/avg/max/mdev = 0.131/0.209/0.452/0.041 ms
```

communication_test:
```
#######################################################
Control command success rate of 10000 samples: 
Max: 1.00
Avg: 1.00
Min: 0.95
#######################################################
```

I am currently operating an FR3 robotic arm using ROS2. During operation, the communication_constraints_violation error occurs frequently. I would like to identify the cause and find a solution.

**Comment by filipul1s** [comment]
I have the same problem. [https://frankaemika.github.io/docs/troubleshooting.html#motion-stopped-due-to-discontinuities-or-communication-constraints-violation](url) has mentioned this problem,  I try to connect the PC directly but the problem still occurs.

**Comment by byeongkyu** [comment]
It is difficult to understand why a single exception causes all launches to terminate. After reviewing the source code, I found that a franka::ControlException occurs while executing robot_->readOnce(). This code is located on line 173 of franka_hardware_interface.cpp. As a temporary measure, I modified this part as follows, and the connection remains stable without any issues.

```
try {
    hw_franka_robot_state_ = robot_->readOnce();
  }
  catch(franka::ControlException &e) {
    RCLCPP_WARN(getLogger(), "Exceptions: %s", e.what());
    return hardware_interface::return_type::OK;
  }
```

**Comment by AndreasKuhner** [comment]
Hi @byeongkyu ,
the problem is that the backend is going into an error mode. So, I don't know how the system is controllable if you do this.

Having communication violations is often caused by some missed details - you might check https://frankaemika.github.io/docs/troubleshooting.html to give some ideas what to check :)

Cheers,
Andreas

**Comment by byeongkyu** [comment]
Hi @AndreasKuhner 

I have tried all the methods from the link you provided, and they all worked. As I initially noted, almost all test results show no errors. What other approaches could there be?

On a different note, I find it hard to understand why a single error should cause all operations to stop. It would be great if there were a way to recover quickly even when a communication violation error occurs.

**Comment by jcarpinelli-bdai** [comment]
We have also seen this issue on multiple arms. The issue started occurring after we upgraded firmware from 5.6 to 5.7.2, and after we upgraded to `libfranka-v0.15.0` and `franka_ros2-v1.0.0`. We have the arms directly connected to each computer. We see this issue consistently after 15 minutes (or so) of the `ros2_control_node` starting. The `communication_test` shows 100% passing.

**Comment by AndreasKuhner** [comment]
@jcarpinelli-bdai Could you maybe change the `communication_test` to not stop after 10 seconds but run e.g. for 20 minutes to see, if you also get there then the communication violation?

**Comment by shr-eyas** [comment]
Facing the same issue, but only when update has some computation going on in it.

**Comment by obiza-theaiinstitute** [comment]
Hi @AndreasKuhner , we ran the communication test that you asked for. I changed the time in `examples/communication_test.cpp` from 10 seconds to 20 minutes.

This is on a real-time Ubuntu machine that is connected to two FR3s by ethernet.
Arm 1:
Control command success rate of 1200000 samples:
Max: 1.00
Avg: 1.00
Min: 0.98

Arm 2:
Control command success rate of 1200000 samples:
Max: 1.00
Avg: 1.00
Min: 0.99

Separately, I ran tests with our Franka ROS driver. The first arm gets a `communication_constraints_violation` in 9 minutes. The second arm in 24 minutes. Running both Franka ROS drivers at once leads to a `communication_constraints_violation` in 9, 11 and 12 minutes in three tests. Hence, we need to restart our bimanual setup once every roughly 10 minutes, which makes working with the FR3s difficult.

**Comment by AndreasKuhner** [comment]
What do you mean by 'our Franka ROS driver'? Do you mean an adapted variant to handle multiple robots on one machine?

In the single robot case, you didn't run into a communication violation?

**Comment by obiza-theaiinstitute** [comment]
> What do you mean by 'our Franka ROS driver'? Do you mean an adapted variant to handle multiple robots on one machine?

We are using the open-source Franka ROS2 driver; “humble” on franka_ros2.
We run it twice with different namespaces on a single real-time machine to control both arms.

> In the single robot case, you didn't run into a communication violation?

Yes, single-arm stations also run into it, usually after 30 minutes.

`communication_constraints_violation` happens frequently with firmware 5.7.2 (libfranka 0.15.0). Downgrading to firmware 5.6.0 (libfranka 0.13.3) fixes it.

**Comment by AndreasKuhner** [comment]
Could you download the logs via Desk and share it with us?

**Comment by joestg** [comment]
This issue still persist. The RAI Institute met with Franka team (Dmitrij Forssilow, Jeremie Tardivon, Kamal Mohy El Dine) on 3/25 to discuss bugs.  
During that meeting, RAI decided to wait until FW 5.8 before further debugging this issue. We choose to roll back to FW 5.6.0 until then, since the bug is not present in 5.6.0. 

I may have wiped out the logs by installing FW 5.6.0 and doing a factory reset.

**Comment by ruoshiwen** [comment]
We met the same problem for two week after a firmware upgrade to 5.7.2. Following your advice @obiza-theaiinstitute , we downgraded to firmware 5.6.0 (libfranka 0.13.3, franka_ros2 0.15.0), now it seems running fine. Many thanks!

**Comment by mrceki** [comment]
Hi all, 
I had the same issue. I tried everything except downgrading the libfranka version. Then I downgraded libfranka to 0.13.3 from 0.13.6, and it's running fine. Thanks!

**Comment by Jelmerdw** [comment]
@obiza-theaiinstitute @ruoshiwen @mrceki 

We are trying to downgrade as well. However, we cannot find this option in Franka Desk or Franka World. Could you elaborate how you downgrade the robot?

**Comment by obiza-theaiinstitute** [comment]
You'd need to talk directly to Franka.

**Comment by kmohyeldine** [comment]
@Jelmerdw  please contact support@franka.de

**Comment by zadaianchuk** [comment]
We encountered a similar problem with libfranka 0.15 and Franka firmware 5.8, so it seems like downgrading is the only option so far

**Comment by AndreasKuhner** [comment]
To everyone in this thread: Last week we released the system image 5.8.1 which improved the communication behavior. Could you guys give it a try and see if it resolves your problems?

A root cause was, that the performance decreased between the 5.6 to the 5.8 and our internal loop took roughly 100us longer than before. We optimized that now and are faster than ever 🥳

**Comment by Jelmerdw** [comment]
@AndreasKuhner 

We tested the release of system image 5.8.1 and this seems to work much better. With this system image, we are also able to use the robot in combination with Jazzy:

https://github.com/frankarobotics/franka_ros2/pull/170

We now encounter the communication_constraints_violation only when we try to move too soon after launching the robot or when we relaunch directly after a previous launch.

**Comment by AndreasKuhner** [comment]
Thank you @Jelmerdw for testing - good to hear about the result :)

Could you elaborate `too soon after launching the robot or when we relaunch directly after a previous launch` a bit more? Especially, what do you mean by 'launching the robot'?

Cheers,
Andreas

**Comment by lusu8892** [comment]
On my end, 5.8.1 robot system did not improve stability (still get communication_constraints_violation)
My setup:
PC running real-time kernal, high performance
ROS2: Humble
franka_ros2: v1.0.0
franka_description: 0.4.0
libfranka: 0.15.0

Communication_test: 100% passed

Tests have ran with ROS2 and franka_ros2:
`franka_fr3_moveit_config moveit.launch.py`, just launch this without sending any trajectory, run 10-15mins then got the error message.
`franka_bringup joint_impedance_example_controller.launch.py`, run 10-15 mins dead.

**Solely running controller example from libfranka does not cause communication_violation at all.......**
Modified joint_impedance_controller running 30mins, no error got.

This may not be conclusive, but look like either Franka_ros2 or ROS2 is not stable........

Please continue working on this issue..

Thanks!

**Comment by AndreasKuhner** [comment]
Hi @lusu8892 ,
thank you for the testing! On the one side, it sounds good that libfranka seems to run stable 👍 

With ROS 2, we already know that is unfortunately not aligned with a 'real time' control scheme. ros2_control is doing a great job but the problem here is: It runs with its own spinning time while libfranka syncs up with the spin of the robot. 
Meaning, with libfranka, after doing the `read`, you get the 'full time' to do your computations and send the next command back. Yet, with ROS 2 you have always a 'sleep' after the 'write' (controlled by ros2_control). This sleep is used to aim for the target frequency. However, that means that your 'read' can get delayed and you don't get the 'full time' to do your computations.

Summary: libfranka + robot in sync, ros2_control + robot **not** in sync 😓

We will still work on it and try to improve it.

**Comment by danielsanjosepro** [comment]
Hey! I was going to give the release 5.8.1 a try but it does not look like it is available when I try to update my system...

**Comment by AndreasKuhner** [comment]
Hi @danielsanjosepro ,
which version are you currently running? 

Cheers,
Andreas

**Comment by danielsanjosepro** [comment]
@AndreasKuhner Sorry for the late answer. I am and was using 5.8.0. But I have not been experiencing this issue for a while. This week however it problem started again on a different FR3 that we own using 5.8.0...

**Comment by danielsanjosepro** [comment]
Has this been fixed by: https://github.com/ros-controls/ros2_control/issues/2529?

**Comment by BarisYazici** [comment]
Our repo franka_ros2 jazzy branch currently have a fork of [controller_manager](https://github.com/frankarobotics/franka_ros2/tree/jazzy/controller_manager) which should have the necessary fix for the Jazzy distro to work with Franka robots

**Comment by bjin-bdai** [comment]
> With ROS 2, we already know that is unfortunately not aligned with a 'real time' control scheme. ros2_control is doing a great job but the problem here is: It runs with its own spinning time while libfranka syncs up with the spin of the robot. Meaning, with libfranka, after doing the `read`, you get the 'full time' to do your computations and send the next command back. Yet, with ROS 2 you have always a 'sleep' after the 'write' (controlled by ros2_control). This sleep is used to aim for the target frequency. However, that means that your 'read' can get delayed and you don't get the 'full time' to do your computations.

@AndreasKuhner this is interesting, so is the implication here that ideally the `ros2_control_node.cpp` loop would just be something like:

```
while (running) {
    cm->read(...);
    cm->update(...);
    cm->write(...);

    // don't sleep because read() will synchronize the loop
}
```

For context, we've run into communication constrain violations with firmware 5.8, but with a `humble` branch, even though `wireshark` data does not show noticeable packet delays between our Linux box and Franka control box

**Comment by bjin-bdai** [comment]
> Our repo franka_ros2 jazzy branch currently have a fork of [controller_manager](https://github.com/frankarobotics/franka_ros2/tree/jazzy/controller_manager) which should have the necessary fix for the Jazzy distro to work with Franka robots

@BarisYazici would it be possible to have this implementation ported to the `humble` branch as well?

**Comment by lianghongzhuo** [comment]
> Our repo franka_ros2 jazzy branch currently have a fork of [controller_manager](https://github.com/frankarobotics/franka_ros2/tree/jazzy/controller_manager) which should have the necessary fix for the Jazzy distro to work with Franka robots

this fix seems not solved the problem on my side, I am using 5.8.2 firmware with ros jazzy. Still get "communication_constraints_violation" error every 30 minutes (in average, some times even quicker)

**Comment by lianghongzhuo** [comment]
> Hi all, I had the same issue. I tried everything except downgrading the libfranka version. Then I downgraded libfranka to 0.13.3 from 0.13.6, and it's running fine. Thanks!


> We met the same problem for two week after a firmware upgrade to 5.7.2. Following your advice [@obiza-theaiinstitute](https://github.com/obiza-theaiinstitute) , we downgraded to firmware 5.6.0 (libfranka 0.13.3, franka_ros2 0.15.0), now it seems running fine. Many thanks!

As many users above have reported. Older firmware versions, like 5.6.0, did not have this problem. We would be interested to know what specific change caused this
@BarisYazici

**Comment by Jelmerdw** [comment]
We also still experience the communication constraints violations error. We use 5.8.2 firmware. We have tested with both Jazzy and Humble using the Docker container installs provided in the README of both branches.

We can successfully use different [example controllers](https://frankarobotics.github.io/docs/franka_ros2/franka_example_controllers/doc/index.html), but we always experience the error when using a joint_trajectory_controller. The easiest way to test this for us is by starting the [moveit example](https://frankarobotics.github.io/docs/franka_ros2/franka_fr3_moveit_config/doc/index.html):

`ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=<fci-ip>`

Even when we only load and activate the joint_trajectory_controller (without sending commands), the error sometimes occurs. It is very inconsistent. Most of the time, the error occurs within a few seconds after activating the joint_trajectory_controller. Sometimes we can do a few movements, but we were never able to last more than a minute before failing again because of the communication constraints violations.

**Comment by BarisYazici** [comment]
To have the same baseline can all of you test the communication with franka_ros2 `gravity_compensation_example` on the 5.8.2 image on Humble or Jazzy distros without another custom controller involved?

**Comment by BarisYazici** [comment]
> As many users above have reported. Older firmware versions, like 5.6.0, did not have this problem. We would be interested to know what specific change caused this

@lianghongzhuo 5.8.2 should already have the fix for the communication issues. The issue you quoted was mentioning the 5.7.2 which had an issue. 5.8.2 should have the same similar performance as 5.6.0. With the upcoming 5.9.0 we will improve it even further.

**Comment by Jelmerdw** [comment]
> To have the same baseline can all of you test the communication with franka_ros2 `gravity_compensation_example` on the 5.8.2 image on Humble or Jazzy distros without another custom controller involved?

We tested the `gravity_compensation_example` on Jazzy with 5.8.2 image. This gave no problems.

We only face the error when using the joint_trajectory_controller.

**Comment by lianghongzhuo** [comment]
> > To have the same baseline can all of you test the communication with franka_ros2 `gravity_compensation_example` on the 5.8.2 image on Humble or Jazzy distros without another custom controller involved?
> 
> We tested the `gravity_compensation_example` on Jazzy with 5.8.2 image. This gave no problems.
> 
> We only face the error when using the joint_trajectory_controller.

I also have this issue, joint_trajectory_controller does not work properly,  `gravity_compensation_example`  I did not test, but I tested `elbow_example_controller` also no error.

**Comment by AndreasKuhner** [comment]
> @AndreasKuhner this is interesting, so is the implication here that ideally the ros2_control_node.cpp loop would just be something like:

@bjin-bdai You hit the spot :) Our libfranka/FCI really puts the user in the middle of the closed control loop. If we now have something, which runs on its own schedule (aka sleeps on its own), there will be an unavoidable drift over time. I think with humble, it can run for a longer time but with our initial push to jazzy, the problem was thrown a lot more in our face. So yes: Ideally, libfranka can do the 'sleep' (will do it anyways) and ros2_control doesn't block or control frequencies.

> this fix seems not solved the problem on my side, I am using 5.8.2 firmware with ros jazzy. Still get "communication_constraints_violation" error every 30 minutes (in average, some times even quicker)

Next week, we will have the image version 5.9.0 release which should contain more juicy updates to ease the issue about `communication_constraint_violations`. Technically, the performance is then back again on 5.6.0 levels (even a little bit better). I hope that resolves the 'new' issues. What we do about jazzy and if we can backport those fixes also to humble, is a bit open.

Cheers,
Andreas

**Comment by BarisYazici** [comment]
> We tested the gravity_compensation_example on Jazzy with 5.8.2 image. This gave no problems.
> 
> We only face the error when using the joint_trajectory_controller.

If you are on jazzy can you enable the introspection tools to diagnose the controllers especially the joint trajectory controller update function? You can visualize the introspection tools on plotjuggler. Can you analyze if there is sth irregular e.g. some spikes in the timings etc. Also please make sure you build everything with the Release flag

**Comment by lianghongzhuo** [comment]
> > We tested the gravity_compensation_example on Jazzy with 5.8.2 image. This gave no problems.
> > We only face the error when using the joint_trajectory_controller.
> 
> If you are on jazzy can you enable the introspection tools to diagnose the controllers especially the joint trajectory controller update function? You can visualize the introspection tools on plotjuggler. Can you analyze if there is sth irregular e.g. some spikes in the timings etc. Also please make sure you build everything with the Release flag

@BarisYazici  Could you give an introduction on how to enable this test? How to enable the introspection tools ?

**Comment by magnusdierking** [comment]
> We also still experience the communication constraints violations error. We use 5.8.2 firmware. We have tested with both Jazzy and Humble using the Docker container installs provided in the README of both branches.
> 
> We can successfully use different [example controllers](https://frankarobotics.github.io/docs/franka_ros2/franka_example_controllers/doc/index.html), but we always experience the error when using a joint_trajectory_controller. The easiest way to test this for us is by starting the [moveit example](https://frankarobotics.github.io/docs/franka_ros2/franka_fr3_moveit_config/doc/index.html):
> 
> `ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=<fci-ip>`
> 
> Even when we only load and activate the joint_trajectory_controller (without sending commands), the error sometimes occurs. It is very inconsistent. Most of the time, the error occurs within a few seconds after activating the joint_trajectory_controller. Sometimes we can do a few movements, but we were never able to last more than a minute before failing again because of the communication constraints violations.

@Jelmerdw Have you tried to adapt the franka_fr3_moveit_config/config/fr3_ros_controllers.yaml ? Just add "enable_overrun: false" as an additional option under the ros_parameters like @BarisYazici did for franka_bringup with commit 99e9a64 to actually apply the hotfix.

**Comment by lianghongzhuo** [comment]
> > We also still experience the communication constraints violations error. We use 5.8.2 firmware. We have tested with both Jazzy and Humble using the Docker container installs provided in the README of both branches.
> > We can successfully use different [example controllers](https://frankarobotics.github.io/docs/franka_ros2/franka_example_controllers/doc/index.html), but we always experience the error when using a joint_trajectory_controller. The easiest way to test this for us is by starting the [moveit example](https://frankarobotics.github.io/docs/franka_ros2/franka_fr3_moveit_config/doc/index.html):
> > `ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=<fci-ip>`
> > Even when we only load and activate the joint_trajectory_controller (without sending commands), the error sometimes occurs. It is very inconsistent. Most of the time, the error occurs within a few seconds after activating the joint_trajectory_controller. Sometimes we can do a few movements, but we were never able to last more than a minute before failing again because of the communication constraints violations.
> 
> [@Jelmerdw](https://github.com/Jelmerdw) Have you tried to adapt the franka_fr3_moveit_config/config/fr3_ros_controllers.yaml ? Just add "enable_overrun: false" as an additional option under the ros_parameters like [@BarisYazici](https://github.com/BarisYazici) did for franka_bringup with commit [99e9a64](https://github.com/frankarobotics/franka_ros2/commit/99e9a6432bccb22eafb80c15b1c917f9325edae4) to actually apply the hotfix.

That is exactly what I misunderstood with @BarisYazici , I thought the by defailt config is the hot fix, and did not add "enable_overrun: false" on my ros2 controller yaml file. I would be exicited to test if this works/fix the 
communication_constraints_violation problem.

I will report once I tested this.

**Comment by BarisYazici** [comment]
`@Jelmerdw Have you tried to adapt the franka_fr3_moveit_config/config/fr3_ros_controllers.yaml ? Just add "enable_overrun: false" as an additional option under the ros_parameters like @BarisYazici did for franka_bringup with commit https://github.com/frankarobotics/franka_ros2/commit/99e9a6432bccb22eafb80c15b1c917f9325edae4 to actually apply the hotfix.`

that's a good catch. We actually forgot to add the enable_overrun to false for the moveit examples. Please add enable_overrun: false parameter to this controller yaml https://github.com/frankarobotics/franka_ros2/blob/humble/franka_fr3_moveit_config/config/fr3_ros_controllers.yaml
We will fix it as soon as possible in the main branch

**Comment by lianghongzhuo** [comment]
Hi @BarisYazici , I am happy to report here: after changing the default option of enable_overrun to false, I did not see a communication constraints violation error again!
Tested on Ros jazzy, FW: 5.8.2, real-time kernel PC.

**Comment by mrceki** [comment]
Hi guys,
I've upgraded my robot to version 5.9.0 and gave it a go with humble, and unfortunately it did fail again with gravity compensation error. Then I rebuild the docker container with jazzy version and it seems like it did the job and I did not get 'communication_constraints_violation' for a while :)

**Comment by Jelmerdw** [comment]
@magnusdierking @BarisYazici 

Adding the `enable_overrun: false` option indeed solves the problem for us!
We tested again on Jazzy, 5.8.2 and can we can use the joint_trajectory_controller without problems now by adding the option.
Thanks a lot for the help!

**Comment by danielsanjosepro** [comment]
Is this update available for all FR3s? I just updated one to Jazzy 5.9.0, and it seems to work fine, but another one doesn’t seem to be able to update past 5.8.0. Is that normal?

**Comment by BarisYazici** [comment]
> Is this update available for all FR3s? I just updated one to Jazzy 5.9.0, and it seems to work fine, but another one doesn’t seem to be able to update past 5.8.0. Is that normal?

yes, it's available for all FR3. Maybe contact support for this, I am unsure what the issue could be?

**Comment by AndreasKuhner** [comment]
If there are still some issues, let us know. At least, momentarily it seems to be fine... :)

Cheers,
Andreas

**Comment by negi-DWA** [comment]
We still have communication constraint violation with Firmware 5.9.2 and we are using franka_ros2 jazzy (v3.4.1) with vs code devcontainer. We tried everything we could think about and read in the github issues:
- Our PC Spec: HP Z4 G5, Intel Xeon w5-2545*12, 128GB Memory
- Ubuntu 24.04.3 LTS, Realtime Kernel 6.14.0-rt3
- we did the communication test from libfranka, it was successful
- we added a separate network ethernet card Intel 82580, and made sure EEE was not active.
- we tried different ethernet cable, cat 7 and cat 6a, 
- we set the cpu to performance mode
- we made sure that overrun in the controller config was set to false
- colcon build with release flag
- we also tried to downgrade to Firmware 5.8.2, franka ros2 jazzy, libfranka 0.17.0
All these didn’t help and we are still having communication constraint violation.
But if we control the robot directly via libfranka without ros2 control, we didn’t have any communication issues.

**Comment by AndreasKuhner** [comment]
Hi @negi-DWA ,
did you guys also add `enable_overrun: false`?

Cheers,
Andreas

**Comment by negi-DWA** [comment]
> Hi [@negi-DWA](https://github.com/negi-DWA) , did you guys also add `enable_overrun: false`?
> 
> Cheers, Andreas

Hi @AndreasKuhner , thanks for the reply, we did add `enable_overrun: false` and still got the error.

**Comment by AndreasKuhner** [comment]
What ping do you get? So the round-trip-time of `ping` ?

**Comment by negi-DWA** [comment]
> What ping do you get? So the round-trip-time of `ping` ?

10000 packets transmitted, 10000 received, 0% packet loss, time 9998ms
rtt min/avg/max/mdev = 0.080/0.129/0.285/0.028 ms

**Comment by lianghongzhuo** [comment]
> > Hi [@negi-DWA](https://github.com/negi-DWA) , did you guys also add `enable_overrun: false`?
> > Cheers, Andreas
> 
> Hi [@AndreasKuhner](https://github.com/AndreasKuhner) , thanks for the reply, we did add `enable_overrun: false` and still got the error.

In the new franka_ros2, the correct way to write this is:
```

      overruns:
        manage: false
        print_warnings: true
```

**Comment by lianghongzhuo** [comment]
On the other hand, I found this :
https://github.com/frankarobotics/franka_ros2/blob/jazzy/patches/manage_overruns.patch
and the change log here wrotes:
> chore: Unify ros2_control (Jazzy) sources to avoid ABI mismatches (add ros2_control to dependency.repos so hardware_interface/controller_manager build from the same ABI;
remove the standalone hardware_interface fork; keep manage_overruns for async hardware components via a small patch auto-applied in franka_entrypoint.sh).
**BREAKING**: existing workspaces must be cleaned before rebuilding: ``rm -rf build/ install/ && colcon build``


Are we still required to patch `ros2_controller` for better performance? ping @BarisYazici

**Comment by negi-DWA** [comment]
> We still have communication constraint violation with Firmware 5.9.2 and we are using franka_ros2 jazzy (v3.4.1) with vs code devcontainer. We tried everything we could think about and read in the github issues:
> 
>     * Our PC Spec: HP Z4 G5, Intel Xeon w5-2545*12, 128GB Memory
> 
>     * Ubuntu 24.04.3 LTS, Realtime Kernel 6.14.0-rt3
> 
>     * we did the communication test from libfranka, it was successful
> 
>     * we added a separate network ethernet card Intel 82580, and made sure EEE was not active.
> 
>     * we tried different ethernet cable, cat 7 and cat 6a,
> 
>     * we set the cpu to performance mode
> 
>     * we made sure that overrun in the controller config was set to false
> 
>     * colcon build with release flag
> 
>     * we also tried to downgrade to Firmware 5.8.2, franka ros2 jazzy, libfranka 0.17.0
>       All these didn’t help and we are still having communication constraint violation.
>       But if we control the robot directly via libfranka without ros2 control, we didn’t have any communication issues.

The communication constraint vioaltion problem is now solved using the same setup but with RT kernel version 6.8.0-rt8.. @AndreasKuhner still thanks for the help.

**Comment by padams20-utk** [comment]
Hello,
My team has also experienced this issue. After poring over this issue, we've decided to add some additional information from our logs that can maybe help resolve this bug.
```

 PC spec: Dell Pro Max 16 MC16250 with Intel Core Ultra 5 235 x 14, 16 GB RAM

 Realtime Kernel 6.17.0-1018-realtime
 
 Ping tests were successful

 We set cpu to performance

 We reserved two performance cores on the cpu specifically for ROS processes

 Colcon build with release flag

 We tried different ethernet cables, as well as a thunderbolt 4 to ethernet converter.

 We are currently connected via ros2 jazzy to a franka research 3 arm

 Our Franka 3 Research system image is 5.10
 
```

Our launch command is as follows: 
```ros2 launch franka_fr3_moveit_config moveit.launch.py   robot_ip:=<robot_ip>```

For reference, I've included an attached text file which represents an example run of the above command, from its start to the point we cancel it with ctrl-c. There were some output messages after the ctrl-c, but we didn't include those, for brevity. 

[ros2_run_logs.txt](https://github.com/user-attachments/files/30515460/ros2_run_logs.txt)

Now, one more note of interest:

Before every overrun, we get this warning message: 
     `[ros2_control_node-4] [WARN] [1785344292.616233076] [controller_manager]: Overrun might occur, Total time : 1040.603 us (Expected < 1000.000 us) --> Read time : 998.277 us, Update time : 26.072 us, Write time : 16.254 us` 
     This message only occurs after we set print_warnings to true, which makes sense. It also occurs about every 1 second. I'd like to highlight here that the "read time" is very high, compared to the others. We're not sure why this is the case, but perhaps this information can be useful.

**Comment by lianghongzhuo** [comment]
Did you patch the ROS 2 controller as mentioned here: https://github.com/frankarobotics/franka_ros2/blob/jazzy/patches/manage_overruns.patch?
Also, as I asked earlier, I'm not sure whether this patch is still required.
I hope Franka Robotics can provide an official response regarding this.

**Comment by padams20-utk** [comment]
Update: 
The patch did not fix anything at first--we were still getting constant overruns. Eventually, though, the robot stopped throwing overrun errors and now works cleanly. We're not sure exactly what we changed, but I think we had overruns: manage set to true for a long time, as we thought turning it off would lead to another issue (which turned out to be an unrelated bug). Earlier this morning, we were able to separate the cause-and-effect of these two bugs and realized we'd left enable_overruns true.

Perhaps that was the issue, or perhaps it was an underlying issue that the patch fixed after all. We can't tell why it's working, but it's good now. Thanks for the support!

**Comment by lianghongzhuo** [comment]
I have made a MR to remove the patch, https://github.com/frankarobotics/franka_ros2/pull/237

**Comment by AndreasKuhner** [comment]
Hi @lianghongzhuo ,
the patch is still needed. Unfortunately, the `realtime_tools` don't support to de-activate the overrun mechanism as of now. 

Cheers,
Andreas
